AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless

  Sample SAM Template for serverless

Resources:
  AuthorsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: authors
      AttributeDefinitions:
        - AttributeName: authorid
          AttributeType: S
      KeySchema:
        - AttributeName: authorid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  GetAuthors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: serverless/
      Handler: authors/getAuthors.handler
      Runtime: nodejs14.x
      Events:
        GetAuthors:
          Type: Api
          Properties:
            Path: /api/v1/authors
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GetAuthors
#        - Version: '2012-10-17'
#          Statement:
#            - Effect: Allow
#              Action:
#                - 'dynamodb:Scan'
#              Resource:
#                'Fn::Join':
#                  - ''
#                  - - 'arn:aws:dynamodb:'
#                    - Ref: 'AWS::Region'
#                    - ':'
#                    - Ref: 'AWS::AccountId'
#                    - ':table/authors'

# DynamoDB tables
#  authorsTable:
#    Type: 'AWS::DynamoDB::Table'
#    Properties:
#      TableName: authors
#      AttributeDefinitions:
#        - AttributeName: authorid
#          AttributeType: S
#      KeySchema:
#        - AttributeName: authorid
#          KeyType: HASH
#      ProvisionedThroughput:
#        ReadCapacityUnits: 5
#        WriteCapacityUnits: 5

Outputs:
  AuthorsApi:
    Description: "API Gateway endpoint URL for Authors API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/v1/authors/"

  GetAuthors:
    Description: "GetAuthors lambda function ARN"
    Value: !GetAtt GetAuthors.Arn
  GetAuthorsIamRole:
    Description: "GetAuthors role for function GetAuthors"
    Value: !GetAtt GetAuthorsRole.Arn
#